
//CURRENT LOCATION
export const CURRENT_LOCATION_REQUEST = 'CURRENT_LOCATION_REQUEST'
export const CURRENT_LOCATION_SUCCESS = 'CURRENT_LOCATION_SUCCESS'
export const CURRENT_LOCATION_FAIL = 'CURRENT_LOCATION_FAIL'

//Geolocation
export const GEO_LOCATION_REQUEST = 'GEO_LOCATION_REQUEST'
export const GEO_LOCATION_SUCCESS = 'GEO_LOCATION_SUCCESS'
export const GEO_LOCATION_FAIL = 'GEO_LOCATION_FAIL'

// AUTOCOMPLETE LOCATIONS
export const AUTOCOMPLETE_LOCATIONS_REQUEST= 'AUTOCOMPLETE_LOCATIONS_REQUEST'
export const AUTOCOMPLETE_LOCATIONS_SUCCESS = 'AUTOCOMPLETE_LOCATIONS_SUCCESS '
export const AUTOCOMPLETE_LOCATIONS_FAIL = 'AUTOCOMPLETE_LOCATIONS_FAIL'

//5-DAY FORECAST
export const FORECAST_LOCATION_REQUEST = 'FORECAST_LOCATION_REQUEST'
export const FORECAST_LOCATION_SUCCESS = 'FORECAST_LOCATION_SUCCESS'
export const FORECAST_LOCATION_FAIL = 'FORECAST_LOCATION_FAIL'

// ADD LOCATION TO FAVORITES
export const ADD_FAVORITES_REQUEST = 'ADD_FAVORITES_REQUEST'
export const  ADD_FAVORITES_SUCCESS = 'ADD_FAVORITES_SUCCESS'
export const  ADD_FAVORITES_FAIL = 'ADD_FAVORITES_FAIL'
export const ADD_FAVORITES_RESET = 'ADD_FAVORITES_RESET'
// REMOVE LOCATION FROM FAVORITES

export const  REMOVE_FAVORITES_REQUEST = 'REMOVE_FAVORITES_REQUEST'
export const  REMOVE_FAVORITES_SUCCESS = 'REMOVE_FAVORITES_SUCCESS'
export const  REMOVE_FAVORITES_FAIL = 'REMOVE_FAVORITES_FAIL'